### ISSUE TITLE
REAME.md typo

### ISSUE THREAD

**Issue by samiare** [samiare/whitewater-mobile-video#7]
1. It *offer* a flexible API with playback methods  
   >It *offers* a flexible API with playback methods

2. Unpack whitewater.zip *it*  and
   >Unpack whitewater.zip and

**Comment by nick-f** [comment]
In the Whitewater Player description:

"recrate video" should be "recreate video".

I've created a [pull request](https://github.com/samiare/whitewater-mobile-video/pull/9) to fix these.

**Comment by samiare** [comment]
Thanks @nick-f. I've merged your changes into the dev branch (4a72655c41f08bbe77c95db8d48429970c8b012f) and will merge them into master once I get a few more changes made.
